<?php
// DO NOT EDIT THIS FILE. IT WILL BE AUTO-GENERATE ITSELF FROM TIME TO TIME.
require 'apipartials/api_route.php';
require 'apipartials/rover_apiroute.php';
require 'apipartials/server_apiroute.php';
require 'apipartials/user_apiroute.php';
