<?php
// DO NOT EDIT THIS FILE. IT WILL BE AUTO-GENERATE ITSELF FROM TIME TO TIME.
require 'partials/panel_route.php';
require 'partials/rover_route.php';
require 'partials/server_route.php';
require 'partials/web_route.php';
