<?php

namespace App\Console\Commands\DNS;

use Illuminate\Console\Command;

class RebuildZones extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'dns:zones:rebuild';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Rebuild Aggregated zones configuration file using indiviual zones already created.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $bindpath = config("endurance.bindpath");
        $zonepath = config("endurance.zonepath");
        $zones = scandir($zonepath);
        unset($zones[0]);
        unset($zones[1]);
        $text = "#This file is autogenerated via Endurance using indiviual zones already created." .PHP_EOL;
        $text .= "################################################################################" .PHP_EOL . PHP_EOL;
        foreach ($zones as $domain) {
            $text .= 'include "' . $zonepath . "/" . $domain . '/info.conf";' . PHP_EOL;
        }
        $text .= PHP_EOL . PHP_EOL;
        $check = file_put_contents($bindpath . "/zones.conf", $text);
        $this->info("Aggregated Zone configuration successfully rebuild. Status: " .  $check);
        

    }
    
}
